-- Crear la base de datos planificación si no existe
DROP DATABASE planificacion;
CREATE DATABASE planificacion;

-- Usar la base de datos planificación
USE planificacion;

-- Crear la tabla proyectos
CREATE TABLE PROYECTO (
    ID_PROYECTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR (100) NOT NULL
);

-- Crear la tabla tareas
CREATE TABLE TAREA (
    ID_TAREA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR (100) NOT NULL,
    FECHA_DE_INICIO DATE NOT NULL,
    FECHA_FINAL DATE NOT NULL,
    DESCRIPCION VARCHAR (500) NOT NULL,
    FK_ID_PROYECTO INT ,
    FOREIGN KEY (FK_ID_PROYECTO) REFERENCES PROYECTO(ID_PROYECTO)
);

CREATE TABLE EMPLEADO (
    ID_EMPLEADO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_EMPLEADO VARCHAR(100) NOT NULL,
    CEDULA_EMPLEADO INT NOT NULL,
    FKCARGO_EMPLEADO INT,
    FECHA_NACIMIENTO DATE NOT NULL,
    FECHA_INICIO_CONTRATO DATE NOT NULL,
    SALARIO_EMPLEADO INT NOT NULL,
    FK_ID_CONTRATO INT,
    ID_TRANSACCION INT,
    FK_ID_DESPIDO INT
);

CREATE TABLE DETALLE_PROYECTO (
    ID_DETALLE_PROYECTO INT AUTO_INCREMENT PRIMARY KEY,
    FK_ID_EMPLEADO INT NOT NULL,
    FK_ID_PROYECTO INT NOT NULL,
    FOREIGN KEY (FK_ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
    FOREIGN KEY (FK_ID_PROYECTO) REFERENCES PROYECTO(ID_PROYECTO)
);

SHOW TABLES;